### ISSUE TITLE
Security Fixes for Assessments

### ISSUE THREAD

**Issue by annuraggg** [annuraggg/Scriptopia-Suite#25]
- Set Clock on Server Side
- Make a note of when user starts assessment, i.e. mark it as ongoing
- Disable f12 Access

**Comment by annuraggg** [comment]
Fix Copy Paste Issue

**Comment by abdulhadishah** [comment]
Tab Switching Causes Statement Card to Go Blank

- Open a problem statement on the website.
- Switch to the "Submission" tab.
- Switch back to the "Statement" tab.

**Comment by annuraggg** [comment]
Pending as of 30/07
