### ISSUE TITLE
Tab Switching Causes Statement Card to Go Blank

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#26]
**Tab Switching Causes Statement Card to Go Blank**

Description:
- Switching the tab from "Statement" to "Submission" and then back to "Statement" causes the entire statement card to go blank, leaving only the problem title visible.

Steps to Reproduce:
- Open a problem statement.
- Switch to the "Submission" tab.
- Switch back to the "Statement" tab.

Expected Behavior:
- The statement card should display the full problem statement content after switching back.

Actual Behavior:
- The statement card goes blank, and only the problem title is visible.

**Comment by abdulhadishah** [comment]
**Created Assessment Visibility Issue**

Description:

- Created assessments are visible to all users on the backend, but on the frontend, they are only visible to the user who created them.

Steps to Reproduce:
- Create an assessment.
- Check the visibility of the assessment on the frontend as different users.

Expected Behavior:
- The created assessment should be visible to authorized users on the frontend.

Actual Behavior:
- The created assessment is only visible to the creator on the frontend.

**Comment by abdulhadishah** [comment]
**Created Assessment Visibility Issue**

Description:
- Created assessments are visible to all users on the backend, but on the frontend, they are only visible to the user who created them.

Steps to Reproduce:
- Create an assessment.
- Check the visibility of the assessment on the frontend as different users.

Expected Behavior:
- The created assessment should be visible to authorized users on the frontend.

Actual Behavior:
- The created assessment is only visible to the creator on the frontend.

**Comment by abdulhadishah** [comment]
**MCQ Creation Requires Minimum Options**

Description:
- During assessment creation, an MCQ can be created with only one option. At least two options should be required for the MCQ to be accepted.

Steps to Reproduce:
- Create an assessment.
- Add an MCQ with only one option.
- Attempt to save the MCQ.

Expected Behavior:
- The system should require at least two options for the MCQ to be accepted.

Actual Behavior:
- The MCQ is accepted with only one option.

**Comment by abdulhadishah** [comment]
**Access Control Allows Blank Name and Email**

Description:
- In assessment creation, the access control for specific candidates accepts blank names and emails, which should not be allowed. Additionally, email validation is needed.

Steps to Reproduce:
- Create an assessment.
- Add a candidate with a blank name and email.
- Attempt to save the assessment.

Expected Behavior:
- The system should not allow saving candidates with blank names and emails and should validate the email format.

Actual Behavior:
- The system accepts and saves candidates with blank names and emails.

**Comment by abdulhadishah** [comment]
**Feedback Section Requires Email Validation**

Description:
- The feedback section in assessment creation must have email validation to ensure valid email addresses are provided.

Steps to Reproduce:
- Create an assessment.
- Add feedback with an invalid email address.
- Attempt to save the assessment.

Expected Behavior:
- The system should validate email addresses in the feedback section before saving.

Actual Behavior:
- The system does not validate email addresses in the feedback section.

**Comment by abdulhadishah** [comment]
**Missing Field Handling in Assessment Creation**

Description:
- When the user does not fill required fields or any fields during assessment creation and clicks "Create Assessment," a popup with "assessment creation error" appears and redirects to the assessments page. Instead, it should inform the user that fields are missing and should not redirect to a new page.

Steps to Reproduce:
-  Create an assessment without filling in the required fields.
- Click "Create Assessment."

Expected Behavior:
- The system should display a message indicating that required fields are missing and stay on the current page.

Actual Behavior:
A popup with "assessment creation error" appears, and the user is redirected to the assessments page.

**Comment by annuraggg** [comment]
Pending as of 30/07

**Comment by annuraggg** [comment]
Fixed.
