### ISSUE TITLE
Warning for Tab Switching During Assessment

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#30]
**Warning for Tab Switching During Assessment**

Description:
- When giving an assessment, whenever the user switches tabs, a warning is displayed. There needs to be a decision on whether to kick the user out after a certain number of tab switches or to simply notify the assessment taker that the user has switched tabs and decide on disqualification.

Steps to Reproduce:
- Start an assessment on the website.
- Switch tabs during the assessment.

Expected Behavior:
- The system should either kick the user out after a set number of tab switches or notify the assessment taker of the tab switch and allow them to decide on disqualification.

Actual Behavior:
- Currently, only a warning is displayed, and there is no clear decision on the consequences of tab switching.

**Comment by abdulhadishah** [comment]
**Save Button Needed for Text MCQ**

Description:
- During the assessment, when answering a text-based MCQ, there is no save button available. As a result, the text is not getting saved, and there is no reflection on the progress bar.

Steps to Reproduce:
- Start an assessment with text-based MCQs.
- Enter text in the MCQ answer field.

Expected Behavior:
- A save button should be available to save the entered text, and the progress bar should reflect the saved answer.

Actual Behavior:
- The text is not saved, and the progress bar does not update.

**Comment by annuraggg** [comment]
Thinking....

**Comment by annuraggg** [comment]
Pending as of 30/07

**Comment by annuraggg** [comment]
No.
