### ISSUE TITLE
**Access Control Allows Blank Name and Email**

### ISSUE THREAD

**Issue by annuraggg** [annuraggg/Scriptopia-Suite#31]
**Access Control Allows Blank Name and Email**

Description:
- In assessment creation, the access control for specific candidates accepts blank names and emails, which should not be allowed. Additionally, email validation is needed.

Steps to Reproduce:
- Create an assessment.
- Add a candidate with a blank name and email.
- Attempt to save the assessment.

Expected Behavior:
- The system should not allow saving candidates with blank names and emails and should validate the email format.

Actual Behavior:
- The system accepts and saves candidates with blank names and emails.

_Originally posted by @abdulhadishah in https://github.com/annuraggg/Scriptopia-Code-2.0/issues/26#issuecomment-2227288431_

**Comment by Spy156** [comment]
Fixed

**Comment by Spy156** [comment]
Fixed. Push to Testing
