### ISSUE TITLE
**Feedback Section Requires Email Validation**

### ISSUE THREAD

**Issue by annuraggg** [annuraggg/Scriptopia-Suite#32]
**Feedback Section Requires Email Validation**

Description:
- The feedback section in assessment creation must have email validation to ensure valid email addresses are provided.

Steps to Reproduce:
- Create an assessment.
- Add feedback with an invalid email address.
- Attempt to save the assessment.

Expected Behavior:
- The system should validate email addresses in the feedback section before saving.

Actual Behavior:
- The system does not validate email addresses in the feedback section.

_Originally posted by @abdulhadishah in https://github.com/annuraggg/Scriptopia-Code-2.0/issues/26#issuecomment-2227288800_

**Comment by Spy156** [comment]
Fixed

**Comment by Spy156** [comment]
Fixed. Push to Testing
