### ISSUE TITLE
Save Button Needed for Text MCQ

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#34]
Description:
- During the assessment, when answering a text-based MCQ, there is no save button available. As a result, the text is not getting saved, and there is no reflection on the progress bar.

Steps to Reproduce:
- Start an assessment with text-based MCQs.
- Enter text in the MCQ answer field.

Expected Behavior:
- A save button should be available to save the entered text, and the progress bar should reflect the saved answer.

Actual Behavior:
- The text is not saved, and the progress bar does not update.

**Comment by Spy156** [comment]
Fixed

**Comment by Spy156** [comment]
Fixed. Push to Testing
