### ISSUE TITLE
Assessment Submission Stuck at Loader

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#35]
Description:
- After clicking "Submit" for an assessment, the submission gets stuck at the loader and throws an error. As a result, the assessment is not getting submitted.

Steps to Reproduce:
- Complete an assessment.
- Click the "Submit" button.

Expected Behavior:
- The assessment should be submitted successfully without errors.

Actual Behavior:
- The submission gets stuck at the loader and throws an error, preventing the assessment from being submitted.

**Comment by annuraggg** [comment]
Fixed. Push to Testing
