### ISSUE TITLE
Reuse of Email Allows Multiple Assessment Attempts

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#36]
Description:
- Accessing the same assessment with an already used email allows the user to take the assessment again.

Steps to Reproduce:
- Use an email to take an assessment.
- Attempt to access the same assessment with the same email.

Expected Behavior:
- The system should not allow the same email to be used for multiple attempts of the same assessment.

Actual Behavior:
- The user is allowed to retake the assessment using the same email.

**Comment by annuraggg** [comment]
Fixed. Push to Testing
