### ISSUE TITLE
Assessment Does Not Close After Timeout

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#37]
Description:
- Assessments do not automatically close after the allotted time has expired.

Steps to Reproduce:
- Start an assessment with a set time limit.
- Wait for the time to expire.

Expected Behavior:
- The assessment should automatically close once the time has expired.

Actual Behavior:
- The assessment remains open even after the time limit has expired.

**Comment by annuraggg** [comment]
Fixed. Push to Testing
