### ISSUE TITLE
Users Can Access Closed Assessments

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#38]
Description:
- Users are able to access and take assessments that are marked as closed, which should not be allowed.

Steps to Reproduce:
- Attempt to access a closed assessment.
- Start the assessment.

Expected Behavior:
- The system should not allow users to start or take closed assessments.

Actual Behavior:
- Users are able to access and take closed assessments.

**Comment by annuraggg** [comment]
Fixed. Push to Testing
