### ISSUE TITLE
Reuse of Email Allows Multiple Assessment Attempts with Incorrect State

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#39]
Description:
- Accessing a new assessment with an email that has already been used for a previous assessment causes the website to treat it as the old assessment, resulting in the old state being saved (i.e., all answers are already submitted).

Steps to Reproduce:
- Use an email to complete an assessment.
- Attempt to access a new assessment with the same email.

Expected Behavior:
- The system should recognize the new assessment attempt and not carry over the state from the old assessment.

Actual Behavior:
- The system treats the new assessment as the old one, saving the old state where all answers are already submitted.

**Comment by annuraggg** [comment]
Fixed. Push to Testing
