### ISSUE TITLE
Array Argument Not Cast to String for Problem Run

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#40]
Description:
- When running a problem, if there is an array in the argument, it is not being cast to a string properly.

Steps to Reproduce:
- Create a problem that takes an array as an argument.
- Run the problem with an array as the input.

Expected Behavior:
- The array argument should be cast to a string properly for processing.

Actual Behavior:
- The array argument is not cast to a string, leading to potential errors in processing.

**Comment by annuraggg** [comment]
Fixed. Push to Testing
