### ISSUE TITLE
Incorrect Message When Attempting to Solve Unavailable Assessment

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#41]
Description:
- When attempting to solve an assessment that is not open to the user, the system incorrectly displays an "Access granted" message instead of indicating that access is not allowed.

Steps to Reproduce:
- Log in with a user account.
- Attempt to access and solve an assessment that is not open to you.
- Observe the message displayed.

Expected Behavior:
- The system should display a message indicating that access to the assessment is not allowed.

Actual Behavior:
- The system incorrectly displays an "Access granted" message when attempting to access an assessment that is not open to the user.

**Comment by annuraggg** [comment]
Pending as of 30/7

**Comment by annuraggg** [comment]
Fixed
