### ISSUE TITLE
Code Counting Wide Spaces Leading to Test Case Errors

### ISSUE THREAD

**Issue by abdulhadishah** [annuraggg/Scriptopia-Suite#42]
Description:
- The code is counting wide spaces (likely referring to excessive whitespace or incorrect handling of whitespace characters) which is causing errors in test cases.

Steps to Reproduce:
- Execute the code with input that includes wide spaces.
- Run test cases that involve whitespace-sensitive operations.
- Note the errors encountered due to incorrect handling of wide spaces.

Expected Behavior:
- The code should handle whitespace correctly according to the requirements specified in the test cases.

Actual Behavior:
- The code is counting wide spaces in a manner that leads to errors in the test cases.

**Comment by annuraggg** [comment]
Can't Repro, Not an Issue
