### ISSUE TITLE
Debug Cohort #1

### ISSUE THREAD

**Issue by annuraggg** [annuraggg/Scriptopia-Suite#60]
1. **Clear Up Stripe**:
- [x] Audit and clean up existing Stripe integration.

2. **Add Lemon Squeezy to the Platform**:
- [x] Integrate Lemon Squeezy for payment processing
- [ ] Decide on a billing plan that suits the platform's needs and integrate it into the system

3. **Performance**:
- [ ] Consider a Caching Strategy by end of the week
- 
4. **Logging**:
- [ ] Contact support to activate new Relic, and imtegrate it to the system

5. **Notifications**:
- [ ] Consider a Notifications Strategy by end of the week. Could use APIs top

6. **Role Based Access Control**:
- [ ] Make sure to **ALWAYS** use RBAC in the backend

**Comment by Spy156** [comment]
Task 1 Done
